-- Store access for staff (ROADMAP Phase 8.6).
--
-- NO ROWS MEANS EVERY STORE, so this table starts empty and nobody's access
-- changes when it lands. A member is scoped only once someone picks stores for
-- them in Settings → Members.
--
-- Deliberately NOT generated by `migrate dev`: the dev database carries an
-- unrelated foreign-key drift on orders.customerId, and a diff would quietly
-- rewrite that constraint too (see the Phase 8.6 notes in docs/ROADMAP.md).

-- CreateTable
CREATE TABLE "membership_warehouses" (
    "membershipId" TEXT NOT NULL,
    "warehouseId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "membership_warehouses_pkey" PRIMARY KEY ("membershipId","warehouseId")
);

-- CreateIndex
CREATE INDEX "membership_warehouses_warehouseId_idx" ON "membership_warehouses"("warehouseId");

-- AddForeignKey
ALTER TABLE "membership_warehouses" ADD CONSTRAINT "membership_warehouses_membershipId_fkey" FOREIGN KEY ("membershipId") REFERENCES "memberships"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "membership_warehouses" ADD CONSTRAINT "membership_warehouses_warehouseId_fkey" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE CASCADE ON UPDATE CASCADE;
